#!/bin/bash

# Check flags
if [[ $# > 0 ]]; then

	if [[ $1 == "schedule" ]]; then
		echo Suggested schedule

		# Just list a few
		for file in $(find . -name *.md | tail -3); do

			echo -n "### "
			basename $file
			cat $file
			echo
		done
	fi

	if [[ $1 == "delete" ]]; then
		
		echo Deleting $2	
	fi

else

	# If not parameters just list the tasks
	for file in $(find . -name *.md); do basename $file; done
fi
