#!/bin/bash

# Check flags
if [[ $1 == "schedule" ]]; then

	echo Suggested schedule

	# Just list a few
	for file in $(find . -name *.md | tail -3); do

		echo -n "### "
		basename $file
		cat $file
		echo
		
		done

else

	# If not parameters just list the tasks
	for file in $(find . -name *.md); do basename $file; done
fi
